site_name: Tomodachi Testcontainers
site_description: Collection of Testcontainers, pytest fixtures and test clients for end-to-end/integration testing for Python Tomodachi framework. A great starting point to learn more about Testcontainers and necessity of integration testing.
site_url: https://github.com/filipsnastins/tomodachi-testcontainers

repo_name: filipsnastins/tomodachi-testcontainers
repo_url: https://github.com/filipsnastins/tomodachi-testcontainers

docs_dir: docs

theme:
  name: material
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
  icon:
    repo: fontawesome/brands/github-alt

plugins:
  - glightbox: null
  - search: null
  - mkdocstrings:
      handlers:
        python:
          options:
            extensions:
              - griffe_typingdoc
            show_root_heading: true
            show_if_no_docstring: true
            inherited_members: false
            members_order: source
            separate_signature: true
            unwrap_annotated: true
            filters: ['!^_']
            merge_init_into_class: true
            docstring_section_style: spacy
            signature_crossrefs: true

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Tomodachi Testcontainers:
      - index.md
      - quickstart.md
      - installation.md
      - features.md
      - configuration-options.md
      - included-testcontainers.md
      - troubleshooting.md
      - development.md
      - resources-and-acknowledgements.md
  - Getting Started:
      - getting-started/testing-simple-app.md
      - getting-started/testing-app-with-backing-services.md
      - getting-started/testing-app-with-collaborator-services.md
      - getting-started/testing-asynchronous-systems.md
      # - getting-started/testing-cronjobs-and-scripts.md # TODO
      - getting-started/choosing-testing-strategy.md
      - getting-started/benefits-and-dangers-of-e2e-tests.md
  - Guides:
      - guides/index.md
      - guides/creating-new-testcontainers.md
      - guides/testing-apps-built-with-other-frameworks.md
      - guides/testing-databases.md
      - guides/testing-repositories.md
      # - guides/ports-and-adapters.md # TODO
      # - guides/creating-app-facade.md # TODO
      # - guides/improving-test-performance.md # TODO
      # - guides/managing-test-isolation.md # TODO
      # - guides/running-testcontainer-tests-in-ci-cd.md # TODO
      - guides/debugging-testcontainers.md
      - guides/forward-container-logs-to-pytest.md
      - guides/exporting-test-coverage.md
      - guides/parallelizing-tests.md
  - Reference - Code API:
      - reference/index.md
      - Containers: reference/containers.md
      - Clients: reference/clients.md
      - Fixtures: reference/fixtures.md
      - Assertions: reference/assertions.md
      - Async Probes: reference/async-probes.md
      - Utils: reference/utils.md
