"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Service(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    UUID_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    uuid: _builtins.str
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        uuid: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "uuid", b"uuid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Service: _TypeAlias = Service  # noqa: Y015

@_typing.final
class Metadata(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MESSAGE_UUID_FIELD_NUMBER: _builtins.int
    PROTOCOL_VERSION_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    TOPIC_FIELD_NUMBER: _builtins.int
    DATA_ENCODING_FIELD_NUMBER: _builtins.int
    message_uuid: _builtins.str
    protocol_version: _builtins.str
    timestamp: _builtins.float
    topic: _builtins.str
    data_encoding: _builtins.str
    def __init__(
        self,
        *,
        message_uuid: _builtins.str = ...,
        protocol_version: _builtins.str = ...,
        timestamp: _builtins.float = ...,
        topic: _builtins.str = ...,
        data_encoding: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data_encoding", b"data_encoding", "message_uuid", b"message_uuid", "protocol_version", b"protocol_version", "timestamp", b"timestamp", "topic", b"topic"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Metadata: _TypeAlias = Metadata  # noqa: Y015

@_typing.final
class SNSSQSMessage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SERVICE_FIELD_NUMBER: _builtins.int
    METADATA_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    data: _builtins.bytes
    @_builtins.property
    def service(self) -> Global___Service: ...
    @_builtins.property
    def metadata(self) -> Global___Metadata: ...
    def __init__(
        self,
        *,
        service: Global___Service | None = ...,
        metadata: Global___Metadata | None = ...,
        data: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["metadata", b"metadata", "service", b"service"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "metadata", b"metadata", "service", b"service"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SNSSQSMessage: _TypeAlias = SNSSQSMessage  # noqa: Y015
