@startuml
!include ./container/containers.puml

skinparam dpi 120

title Container Diagram - Application with Relational Database

appContainer()
relationalDbContainer()

Rel_R(app, relationalDb, "Reads from and writes to", "SQLAlchemy")

@enduml
