@startuml
!include <C4/C4_Container>

!procedure appContainer()
    Container(app, "Application", "Python, tomodachi")
!endprocedure

!procedure fileStoreAppContainer()
    Container(fileStoreApp, "File Store Application", "Python, tomodachi", "Provides a text-based file storage service.")
!endprocedure

!procedure orderAppContainer()
    Container(orderApp, "Order Management Application", "Python, tomodachi", "Manages order lifecycle.")
!endprocedure

!procedure orderAppExtContainer()
    Container_Ext(orderExtApp, "Order Management Application", "", "Manages order lifecycle.")
!endprocedure

!procedure customerAppContainer()
    Container(customerApp, "Customer Management Application", "Python, tomodachi", "Manages customer lifecycle.")
!endprocedure

!procedure creditCheckAppContainer()
    Container_Ext(creditCheckApp, "Credit Check Application", "", "Keeps track of customer's credit score.")
!endprocedure

!procedure relationalDbContainer()
    ContainerDb(relationalDb, "Relational database", "PostgreSQL", "Datastore.")
!endprocedure

!procedure dynamoDbContainer()
    ContainerDb(dynamoDb, "DynamoDB key-value database", "DynamoDB", "Datastore.")
!endprocedure

!procedure externalSftpContainer()
    Container_Ext(externalSftp, "Client SFTP server", "SFTP", "Files provided by a client.")
!endprocedure

!procedure s3BucketContainer()
    Container(s3Bucket, "S3 bucket", "AWS S3", "Internal file storage.")
!endprocedure

!procedure awsSnsSqsContainer()
    ContainerQueue(awsSnsSqs, "AWS SNS/SQS message bus", "AWS SNS/SQS", "AWS managed asynchronous message bus.")
!endprocedure

@enduml
