@startuml
!include <C4/C4_Container>

!procedure appContainer()
    Container(app, "Application", "Python, tomodachi")
!endprocedure

!procedure fileStoreAppContainer()
    Container(fileStoreApp, "File Store Application", "Python, tomodachi", "Provides a text-based file storage service.")
!endprocedure

!procedure relationalDbContainer()
    ContainerDb(relationalDb, "Relational database", "PostgreSQL", "Datastore.")
!endprocedure

!procedure dynamoDbContainer()
    ContainerDb(dynamoDb, "DynamoDB key-value database", "DynamoDB", "Datastore.")
!endprocedure

!procedure externalSftpContainer()
    Container_Ext(externalSftp, "Client SFTP server", "SFTP", "Files provided by a client.")
!endprocedure

!procedure s3BucketContainer()
    Container(s3Bucket, "S3 bucket", "AWS S3", "Internal file storage.")
!endprocedure

@enduml
