[tool.poetry]
name = "src"
version = "0.0.0"
description = ""
authors = ["Filips Nastins <nastinsfilips@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
asyncssh = "^2.14.2"
pydantic = "^2.0.2"
structlog = "^23.1.0"
tomodachi = "^0.26.1"
types-aiobotocore = { extras = [
    "dynamodb",
    "s3",
    "sns",
    "sqs",
], version = "^2.5.2" }
types-aiobotocore-dynamodb = "2.5.2"
uvloop = "^0.19.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.4"
pytest-asyncio = "0.21.1" # https://github.com/pytest-dev/pytest-asyncio/issues/706

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
log_level = "INFO"
env = [
    # Set dummy AWS credentials so that we don't accidentally mutate real infrastructure
    "AWS_REGION=us-east-1",
    "AWS_DEFAULT_REGION=us-east-1",
    "AWS_ACCESS_KEY_ID=testing",
    "AWS_SECRET_ACCESS_KEY=testing",
    "AWS_SECURITY_TOKEN=testing",
    "AWS_SESSION_TOKEN=testing",
    # Testcontainers configuration
    "DOCKER_BUILDKIT=1",
    "TESTCONTAINER_DOCKER_NETWORK=tomodachi-testcontainers",
    "TOMODACHI_TESTCONTAINER_DOCKERFILE_PATH=docs_src/Dockerfile",
    "TOMODACHI_TESTCONTAINER_DOCKER_BUILD_CONTEXT=docs_src",
]
