name: main

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      TESTCONTAINER_DOCKER_NETWORK: tomodachi-testcontainers
      DOCKER_BUILDKIT: 1
    strategy:
      max-parallel: 5
      matrix:
        python-version: ['3.11', '3.12', '3.13', '3.14']

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          version: '0.11.21'
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install dependencies - production
        run: |
          uv sync --no-default-groups
          uv pip list

      - name: Test package imports
        run: |
          uv run python -c "import tomodachi_testcontainers"
          uv run python -c "import tomodachi_testcontainers.clients"
          uv run python -c "import tomodachi_testcontainers.containers"
          uv run python -c "import tomodachi_testcontainers.fixtures"
          uv run python -c "import tomodachi_testcontainers.assertions"
          uv run python -c "import tomodachi_testcontainers.async_probes"
          uv run python -c "import tomodachi_testcontainers.utils"

      - name: Install dependencies - dev and extas
        run: |
          uv sync --all-extras
          uv pip list

      - name: Test build step
        run: uv build

      - name: Run commit hooks
        run: SKIP=test uv run make hooks

      - name: Create Docker network for running Testcontianers
        run: docker network create ${{ env.TESTCONTAINER_DOCKER_NETWORK }}

      - name: Run tests
        run: uv run make test-ci

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
